language: emacs-lisp
before_install:
  # install evm
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"

  # install emacs 24
  - evm install emacs-24.4-bin --use --skip

  # install cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"

  # install emacs
  - evm install $EVM_EMACS --use --skip

  # setup cask
  - cask
  - cask clean-elc
  - cask build
script:
  - emacs --version
  - cask exec ert-runner
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
