language: emacs-lisp
sudo: false
before_install:
  # install evm
  - curl -fsSL https://raw.githubusercontent.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp

  # install emacs
  - evm install $EVM_EMACS --use --skip

  # install cask
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"

  # setup cask
  - cask
script:
  - emacs --version
  - if [ $COVERALLS = "yes" ]; then make coverage; else make full-test; fi
env:
  - EVM_EMACS=emacs-24.5-travis COVERALLS=no
  - EVM_EMACS=emacs-25.3-travis COVERALLS=no
  - EVM_EMACS=emacs-26.1-travis COVERALLS=no
  - EVM_EMACS=emacs-26.1-travis COVERALLS=yes
